[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
tokio = { version = "1.40.0", features = ["full"] }
